"""empty message

Revision ID: 8ff19e54205b
Revises: 96ff8555f730
Create Date: 2025-01-17 06:56:17.742137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff19e54205b'
down_revision = '96ff8555f730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('diameter', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=250), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')
        batch_op.drop_column('population')
        batch_op.drop_column('climate')
        batch_op.drop_column('mass')

    # ### end Alembic commands ###
